version: '3'

services:
  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "mysql"
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - ./database:/docker-entrypoint-initdb.d

  # Node.js API Service
  api:
    build:
      context: ./api
    container_name: api_container
    depends_on:
      - mysql
    environment:
      PORT: 3008
      MYSQL_HOST: "mysql"
      MYSQL_PORT: 3306
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "mysql"
    ports:
      - "3008:3008"
    networks:
      - my_network

  # Next.js Frontend Service
  frontend:
    build:
      context: ./next-app
    container_name: frontend_container
    environment:
      PORT: 3000
    ports:
      - "8080:3000"
    networks:
      - my_network
    depends_on:
      - api

networks:
  my_network:
    driver: bridge
